# Generated by Django 4.1.6 on 2023-02-05 07:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('footer', django_ckeditor_5.fields.CKEditor5Field(max_length=1024)),
                ('header', django_ckeditor_5.fields.CKEditor5Field(max_length=1024)),
                ('facebook', models.CharField(max_length=64)),
                ('instagram', models.CharField(max_length=64)),
                ('telegram', models.CharField(max_length=64)),
                ('linkedin', models.CharField(max_length=64)),
                ('github', models.CharField(max_length=64)),
                ('gitlab', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
